# Generated by Django 4.1.5 on 2023-05-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('IDComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=20)),
                ('costo_direccionComuna', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('IDDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDireccion', models.CharField(max_length=20)),
                ('N_de_Direccion', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=30)),
                ('nombre_municipio', models.CharField(max_length=20)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('IDMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('IDPreguntas', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePreguntas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('IDRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('IDRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IDUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=20)),
                ('apellidoUsuario', models.CharField(max_length=20)),
                ('rutUsuario', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('Correo', models.EmailField(max_length=20)),
                ('clave', models.CharField(max_length=30)),
                ('respuesta', models.CharField(max_length=30)),
                ('Preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('IDVenta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fecha_despacho', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('carrito', models.IntegerField()),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_ropa',
            fields=[
                ('IDTipo_de_ropa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipo_de_ropa', models.CharField(max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('IDProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=35)),
                ('stock', models.IntegerField()),
                ('talla', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='PaginaWebb-django')),
                ('tipo_de_ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_de_ropa')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('IDDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('sub_total', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
    ]
